### ISSUE TITLE
await delay?

### ISSUE THREAD

**Issue by seadiem** [swiftforarduino/community#10]
while(true){
  await delay(400)
}

?

**Comment by seadiem** [comment]
Perhaps maybe it will to make a receiver that asynchronously receives data from several radio transmitters

**Comment by carlos4242** [comment]
Hi,

Thanks for the suggestion.



Swift for Arduino currently only supports version 5.3 of swift and those features are swift 5.5 and later, so that code will not compile I'm afraid.

We do not have plans to introduce async programming in swift for arduino as the products we support are all single core, realtime, bare metal (no RTOS overhead), so it wouldn't give any benefit.

The delay function locks the CPU exclusively for a specific timeframe, so it's hard to see what async would achieve here?



I hope you're having fun writing Swift For Arduino programs. Great!
